components = {
    [`WEAPON_PISTOL`] = { suppressor = `component_at_pi_supp_02`, grip = nil},
    [`WEAPON_PISTOL50`] = { suppressor = `COMPONENT_AT_AR_SUPP_02`, grip = nil},
    [`WEAPON_COMBATPISTOL`] = { suppressor = `COMPONENT_AT_PI_SUPP`, grip = nil},
    [`WEAPON_APPISTOL`] = { suppressor = `COMPONENT_AT_PI_SUPP`, grip = nil},
    [`WEAPON_HEAVYPISTOL`] = { suppressor = `COMPONENT_AT_PI_SUPP`, grip = nil},
    [`WEAPON_VINTAGEPISTOL`] = { suppressor = `COMPONENT_AT_PI_SUPP`, grip = nil},
    [`WEAPON_SMG`] = { suppressor = `COMPONENT_AT_PI_SUPP`, grip = nil},
    [`WEAPON_MICROSMG`] = { suppressor = `COMPONENT_AT_AR_SUPP_02`, grip = nil},
    [`WEAPON_ASSAULTSMG`] = { suppressor = `COMPONENT_AT_AR_SUPP_02`, grip = nil},
    [`WEAPON_ASSAULTRIFLE`] = { suppressor = `COMPONENT_AT_AR_SUPP_02`, grip = `COMPONENT_AT_AR_AFGRIP`},
    [`WEAPON_CARBINERIFLE`] = { suppressor = `COMPONENT_AT_AR_SUPP`, grip = `COMPONENT_AT_AR_AFGRIP`},
    [`WEAPON_ADVANCEDRIFLE`] = { suppressor = `COMPONENT_AT_AR_SUPP`, grip = nil},
    [`WEAPON_SPECIALCARBINE`] = { suppressor = `COMPONENT_AT_AR_SUPP_02`, grip = `COMPONENT_AT_AR_AFGRIP`},
    [`WEAPON_BULLPUPRIFLE`] = { suppressor = `COMPONENT_AT_AR_SUPP`, grip = `COMPONENT_AT_AR_AFGRIP`},
    [`WEAPON_ASSAULTSHOTGUN`] = { suppressor = `COMPONENT_AT_AR_SUPP`, grip = `COMPONENT_AT_AR_AFGRIP`},
    [`WEAPON_HEAVYSHOTGUN`] = { suppressor = `COMPONENT_AT_AR_SUPP_02`, grip = `COMPONENT_AT_AR_AFGRIP`},
    [`WEAPON_BULLPUPSHOTGUN`] = { suppressor = `COMPONENT_AT_AR_SUPP_02`, grip = `COMPONENT_AT_AR_AFGRIP`},
    [`WEAPON_PUMPSHOTGUN`] = { suppressor = `COMPONENT_AT_SR_SUPP`, grip = nil},
    [`WEAPON_MARKSMANRIFLE`] = { suppressor = `COMPONENT_AT_AR_SUPP`, grip = `COMPONENT_AT_AR_AFGRIP`},
    [`WEAPON_SNIPERRIFLE`] = { suppressor = `COMPONENT_AT_AR_SUPP_02`, grip = nil},
    [`WEAPON_COMBATPDW`] = { suppressor = nil, grip = `COMPONENT_AT_AR_AFGRIP`}
}
